#!/usr/bin/env python
from __future__ import print_function

import os
import re
import sys
import glob
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--category", default="default", help="note category")
    parser.add_argument("topic", nargs="+")
    args = parser.parse_args()

    files = glob.glob(os.path.join(args.category, "*.md"))
    indexes = [int(re.match("^[a-zA-Z0-9_-]+\/(\d+)", x).group(1)) for x in files]
    if len(indexes) == 0:
        max_index = 0
    else:
        max_index = max(indexes)

    new_index = max_index + 1

    fname = str(new_index) + "-" + "-".join(args.topic) + ".md"
    full_fname = os.path.join(args.category, fname)
    with open(full_fname, "w") as f:
        f.write("# " + " ".join(args.topic))
        print("created file {}".format(full_fname))


if __name__ == "__main__":
    main()
